### ISSUE TITLE
Renew Certificate Ads Betarena and API Narratives

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#10]
@migbash 

We need to renew the certificates for:

apinarratives.betarena.com
ads.betarena.com
sitemap.betarena.com

**Comment by migbash** [comment]
**🟧 UPDATE**

Target `certifiactes` regenreated.

**Comment by migbash** [comment]
via Hubstaff
User: Miguel Bacharov

Project: boilerplate - https://app.hubstaff.com/projects/3036748
Date Range: 06/12/24 - 06/12/24
Work session total: 0:18:24
Billable: Yes

Grand total: 0:18:24

**Comment by migbash** [comment]
via Hubstaff
User: Miguel Bacharov

Project: boilerplate - https://app.hubstaff.com/projects/3036748
Date Range: 06/12/24 - 06/12/24
Work session total: 0:09:13
Billable: Yes

Grand total: 0:27:37
