### ISSUE TITLE
[Bug]: No image behaviour content section

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, when the image is missing, the design gets issues, check the images:

https://scores.betarena.com/a/betarena-soccer/peru-vs-canada-betting-tip-2024-19040236-1719065271
https://scores.betarena.com/a/betarena-soccer/peru-vs-canada-betting-tip-2024-19040236-1719065271

![Screenshot 2024-06-26 at 16 45 40](https://github.com/Betarena/boilerplate/assets/37311649/4cbf0f88-c569-4b3d-b771-cb69b49854e2)
![Screenshot 2024-06-26 at 16 45 25](https://github.com/Betarena/boilerplate/assets/37311649/2150f155-455c-4e0b-b909-980aa8cdd252)

### 🤔 Expected Behavior

Should follow the correct design when images are not defined or with issues:

![Screenshot 2024-06-26 at 16 48 28](https://github.com/Betarena/boilerplate/assets/37311649/dd6f4984-a1bd-4108-99e1-4f44a2f35115)

On tags, the same logic and inside the articles, we just don't load the image-defined space.

### What environment is the bug/issue detected in.

- [X] 🟥 Production (scores.betarena.com)
- [ ] 🟦 Development

### What browsers are you seeing the problem on?

- [X] 💥 All Browsers
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 💥 All Devices
- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/a/betarena-soccer/peru-vs-canada-betting-tip-2024-19040236-1719065271
https://scores.betarena.com/a/betarena-soccer/peru-vs-canada-betting-tip-2024-19040236-1719065271

**Comment by jonsnowpt** [comment]
@Izobov 

The author's position is now inverted on the desktop; please be careful with these changes since they are not expected to be tested.



![Image](https://github.com/Betarena/boilerplate/assets/37311649/e69a59b5-95db-43eb-88ad-05921dd1f935)
![Image](https://github.com/Betarena/boilerplate/assets/37311649/62c419b2-b89a-48a1-9915-f1de62a95685)

**Comment by Izobov** [comment]
@jonsnowpt only affects articles without images. My fault, I should have asked (perhaps there was a clouding of my mind))

I thought the author information looked better at the top without the picture. It wasn't seamless for me...
But again, I had to ask, sorry

![Image](https://github.com/Betarena/boilerplate/assets/54995954/51ed6dd9-3650-4ca6-9d43-6b547af5ee9c)

**Comment by jonsnowpt** [comment]
@Izobov 

For consistency purposes, it should be kept in the usual place.

**Comment by jonsnowpt** [comment]
Tested and working correctly.
