### ISSUE TITLE
[FEATURE]: Add the about and name into the user profile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#30]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We will be adding the fields that allow users to add a bio and name to their profiles.

This information should be added to the Firestore profile section.

<img width="1121" alt="Screenshot 2024-07-16 at 19 39 26" src="https://github.com/user-attachments/assets/0cb4c4d1-a47a-4864-84be-c50955a97e90">

Figma desktop:

https://www.figma.com/design/mKc4K8apc7UkAN99fopLzl/BTA-Design-Scores-Desktop?node-id=389-251324&t=D9YVnismMw0N8Bdf-1

Figma Tablet:

https://www.figma.com/design/joKBgfdQZd4gLHFCPXNffw/BTA-Design-Scores-Tablet?node-id=0-1&t=yXmGjTp61SvgYg0P-1

Figma Mobile:

https://www.figma.com/design/thLKCrDNpVADLdkau4WxCy/BTA-Design-Scores-Mobile?node-id=0-1&t=4MPHt478idkMcBif-1

Fields from the DB:

```
name_2 
name_2_form_field 
name_description 
about 
about_description 
about_form_field 
```

Endpoint:

`betarena_prod   public   profile_translations `

Acceptance Criteria:

- [x] Add the fields into the frontend;
- [x] Add the information to the profile in Firestore;
- [x] Limit the number of characters that the user is able to add to the about form;
- [x] Use this information to populate the user author profile;
- [x] Form fields should follow the same logic as other fields with the error alerts;

**Comment by Izobov** [comment]
@jonsnowpt Is it possible not to change the size when changing the theme? This is probably a designer mistake

![image](https://github.com/user-attachments/assets/e3a28158-daf7-4772-9c5d-39c8eb3805ac)
![image](https://github.com/user-attachments/assets/0cb39ae9-3ab2-48e9-b704-350dcb1e7b47)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 1. Form fields not working on Firefox;


1. 

![Image](https://github.com/user-attachments/assets/d233eeb2-6ff7-47a7-a1f6-af316c33878d)
