### ISSUE TITLE
[FEATURE]: Add the Sportstacks links to the SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#35]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We need to add the Sportstacks links into the SEO HTML result:

- [x] Sports content home;
- [x] Tags;

**Comment by Izobov** [comment]
I also added  tags links (they where missing)

**Comment by jonsnowpt** [comment]
@Izobov 

This is missing on the article page:

https://betarena-scores-platform.herokuapp.com/a/betarena-tennis/hunter-reese-divij-sharan-vs-jeevan-nedunchezhiyan-n-vijay-sundar-prashanth-forecast-2024-porto-portugal-doubles-y0or5of8e9elmwz-1722406624
