### ISSUE TITLE
[Bug]: Sports Content Section Incorrect Order

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The content order needs to be corrected; on the second load, the content loaded is not from the correct date.

https://scores.betarena.com/a/content

![Screenshot 2024-12-02 at 08 59 05](https://github.com/user-attachments/assets/780ecdef-5dd2-42b8-98fa-2afe91a3ded7)

### 🤔 Expected Behavior

The second load should load content using the correct date and order.

**Comment by Izobov** [comment]
@jonsnowpt not a bug.
1st is time to read and 2nd - time ago
![Image](https://github.com/user-attachments/assets/2da4d40a-9b73-437a-9e32-0c378f99010d)

**Comment by Izobov** [comment]
@jonsnowpt  not a bug
1st is time to read 2nd ist time ago
![Image](https://github.com/user-attachments/assets/f78471d1-9191-4cc6-be98-bcf83418c542)

**Comment by jonsnowpt** [comment]
Issue identified.
