### ISSUE TITLE
[FEATURE]: New Authors Profile Section Data Request

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#9]
![Screenshot 2024-06-10 at 16 09 14](https://github.com/Betarena/boilerplate/assets/37311649/bbce2be0-4371-4f2f-81d5-43d759534acd)

### 📝 Feature Request Description

We will be adding the new profile section for the user/author section.

We will need to add new data to the Firestore User Data:

- [x] 1. Add the Name field
- [x] 2. Add the Followers and Following data
- [x] 3. Add the subscribers info into the authors table;
- [x] 4. Add an about field into the user Firestore data;
- [x] 5. Prepare all the data to be available on scores-lib to be consumed from the frontend;

1. The user at this time has the username and now we will also be adding the name that the user will be able to customize.

This data will be added to the user data on Firestore.

`name "Super Jon"`

When the user creates the account, we generate random data for the username, and we will use this data to populate the user name until the user decides to customize it.

2. Users will now be able to follow other users and this data will be added into the Firestore data:

Example:

```
followers

0
date
25 de dezembro de 2023 às 03:06:06 UTC
(timestamp)

uid
"n65vqAoretrrtteIH3b7lsU5454545445f4zroxjHk0SSp2"
(string)

1
date
25 de dezembro de 2023 às 14:11:53 UTC
uid
""n65vqAoretrrtteIH3b7lsU5454545445f4zroxjHiiik0SSp2"
```

```
following

0
date
25 de dezembro de 2023 às 03:06:06 UTC
(timestamp)

uid
"n65vqAoretrrtteIH3b7lsU5454545445f4zroxjHk0SSp2"
(string)

1
date
25 de dezembro de 2023 às 14:11:53 UTC
uid
""n65vqAoretrrtteIH3b7lsU5454545445f4zroxjHiiik0SSp2"
```

3. Users now will be able to subscribe to sportstacks / publications, this data will be in json format and added to the author's table:

`betarena_prod   authors   authors`

`subscribers`

We just need to add and remove the users UID when they subscribe on the frontend. 

4. We will also adding a form field into the user profile where the user can add some info about them;

5. We need to add the data to the scores-lib to be able to prepare the frontend.

Figma file:

https://www.figma.com/design/KLZ8I88MggBM3YpHi8jSzj/BTA-Betarena?m=dev&node-id=0-1

**Comment by migbash** [comment]
**🟧 UPDATE**

Points `5.` only applies to `3.`.
The reason being, `firebase` logic is mostly frontend related (in this case at least for this `issue`) and can be implemented by @Izobov (points `1.`, `2.`, `4.`)

Hence, `5.` (and `3.` respectively) are ready, on next `scores-lib` release.
